<?php

namespace App\Repository\Quiz;

use App\Entity\Quiz\Quiz;
use App\Entity\Quiz\UserResponse;
use App\Entity\Quiz\Winner;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\Query\Expr\Join;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * QuizRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizRepository extends ServiceEntityRepository
{
    /**
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Quiz::class);
    }

    /**
     * @return int
     */
    public function getMaxRank(): int
    {
        $maxRank = $this
            ->createQueryBuilder('quiz')
            ->select('MAX(quiz.rank)')
            ->getQuery()
            ->getSingleScalarResult()
        ;

        return $maxRank ?? 0;
    }

    /**
     * @param int $userId
     *
     * @return Quiz[]|array
     */
    public function getQuizOverForUserId(int $userId): array
    {
        $queryBuilder = $this->createQueryBuilder('quiz');

        $queryBuilder
            ->join(
                Winner::class,
                'winner',
                Join::WITH,
                $queryBuilder->expr()->andX(
                    $queryBuilder->expr()->eq('winner.quiz', 'quiz'),
                    $queryBuilder->expr()->eq('winner.user', ':userId')
                )
            )
            ->setParameter('userId', $userId)
        ;

        return $queryBuilder->getQuery()->getResult();
    }

    /**
     * @param int $userId
     *
     * @return Quiz[]|array
     */
    public function getQuizInProgressForUserId(int $userId): array
    {
        $queryBuilder = $this->createQueryBuilder('quiz');

        $queryBuilder
            ->join(UserResponse::class, 'userResponse', Join::WITH, $queryBuilder->expr()->eq('userResponse.user', ':userId'))
            ->join('userResponse.response', 'response', Join::WITH, $queryBuilder->expr()->eq('response.quiz', 'quiz'))
            ->setParameter('userId', $userId)
        ;

        return $queryBuilder->getQuery()->getResult();
    }
}
