<?php

namespace App\Repository\Quiz;

use App\Entity\Quiz\Quiz;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * QuizRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuizRepository extends ServiceEntityRepository
{
    /**
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Quiz::class);
    }

    /**
     * @return int
     */
    public function getMaxRank(): int
    {
        $maxRank = $this
            ->createQueryBuilder('quiz')
            ->select('MAX(quiz.rank)')
            ->getQuery()
            ->getSingleScalarResult()
        ;

        return $maxRank ?? 0;
    }
}
