<?php

namespace App\Repository\Quiz;

use App\Entity\Quiz\Winner;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * WinnerRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WinnerRepository extends ServiceEntityRepository
{
    /**
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Winner::class);
    }

    /**
     * @param int $quizId
     *
     * @return array
     */
    public function getWinnersForQuizId(int $quizId): array
    {
        return $this
            ->createQueryBuilder('winner')
            ->join('winner.quiz', 'quiz')
            ->where('quiz.id = :quizId')
            ->setParameter('quizId', $quizId)
            ->getQuery()
            ->getResult()
        ;
    }

    /**
     * @param int $quizId
     */
    public function removeWinnersForQuizId(int $quizId)
    {
        $winners = $this->getWinnersForQuizId($quizId);

        foreach ($winners as $winner) {
            $this->_em->remove($winner);
        }

        $this->_em->flush();
    }

    /**
     * @param int $userId
     *
     * @return array
     */
    public function getWinnersForUserId(int $userId): array
    {
        return $this
            ->createQueryBuilder('winner')
            ->join('winner.user', 'user')
            ->where('user.id = :userId')
            ->setParameter('userId', $userId)
            ->getQuery()
            ->getResult()
        ;
    }

    /**
     * @param int $userId
     */
    public function removeWinnersForUserId(int $userId)
    {
        $winners = $this->getWinnersForUserId($userId);

        foreach ($winners as $winner) {
            $this->_em->remove($winner);
        }

        $this->_em->flush();
    }
}
