doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8mb4
        mapping_types:
            enum: string
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        dql:
            datetime_functions:
                 date: DoctrineExtensions\Query\Mysql\Date
                 date_format: DoctrineExtensions\Query\Mysql\DateFormat
                 datediff: DoctrineExtensions\Query\Mysql\DateDiff
                 day: DoctrineExtensions\Query\Mysql\Day
                 hour: DoctrineExtensions\Query\Mysql\Hour
                 now: DoctrineExtensions\Query\Mysql\Now
                 month: DoctrineExtensions\Query\Mysql\Month
                 year: DoctrineExtensions\Query\Mysql\Year
            numeric_functions:
                power: DoctrineExtensions\Query\Mysql\Power
