version: '3.6'

services:

  nginx:
    ports:
      - '80:80'

  mysql:
    volumes:
      - ~/database/sitarium:/var/lib/mysql
    ports:
      - '3306:3306'

  # .env.local > MAILER_DSN=smtp://mail:1025
  mail:
    image: schickling/mailcatcher
    network_mode: bridge
    ports:
      - '1080:1080'
