version: "3.6"

services:
  nginx:
    image: nginx:1.19
    network_mode: bridge
    volumes:
      - ./docker/nginx/sitarium.conf:/etc/nginx/conf.d/sitarium.conf:ro
      - ./public:/www/public
    environment:
      NGINX_HOST: sitarium.local
    ports:
      - 80:80
    links:
      - php

  node:
    image: node:14.15.5
    network_mode: bridge
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app

  php:
    image: sitarium_php
    build: docker/php
    network_mode: bridge
    volumes:
      - .:/www
    environment:
      APP_ENV: dev
      APP_DEBUG: 1
    links:
      - mysql

  mysql:
    image: mysql:5.7
    network_mode: bridge
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sitarium
