<?php

namespace App\Repository;

use App\Entity\User;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Pagerfanta\Adapter\DoctrineORMAdapter;
use Pagerfanta\Pagerfanta;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * UserRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends ServiceEntityRepository
{
    /**
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, User::class);
    }

    /**
     * @param string $name
     * @param int $page
     * @param int $maxPerPage
     *
     * @return Pagerfanta
     */
    public function getPager(?string $name = null, int $page = 1, int $maxPerPage = 20): Pagerfanta
    {
        $queryBuilder = $this->createQueryBuilder('user');

        if (null !== $name) {
            $queryBuilder->andWhere($queryBuilder->expr()->orX(
                sprintf('user.firstname like \'%%%s%%\'', $name),
                sprintf('user.lastname like \'%%%s%%\'', $name)
            ));
        }

        $queryBuilder
            ->addOrderBy('user.firstname')
            ->addOrderBy('user.lastname')
        ;

        $paginator = new Pagerfanta(new DoctrineORMAdapter($queryBuilder));
        $paginator->setMaxPerPage($maxPerPage);
        $paginator->setCurrentPage($page);

        return $paginator;
    }
}
