<?php

namespace App\Repository\Tagline;

use App\Entity\Tagline\Movie;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * MovieRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends ServiceEntityRepository
{
    /**
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Movie::class);
    }

    /**
     * @param int $tmdbId
     *
     * @return Movie[]|array
     */
    public function findByGenre(int $tmdbId): array
    {
        $queryBuilder = $this->createQueryBuilder('movie');

        $queryBuilder
            ->innerJoin('movie.genres', 'genre')
            ->where('genre.tmdbId = :genreId')
            ->setParameter('genreId', $tmdbId)
            ->orderBy('movie.title')
        ;

        return $queryBuilder->getQuery()->getResult();
    }
}
