<?php

namespace App\Repository\Tagline;

use App\Entity\Tagline\Movie;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;
use Pagerfanta\Doctrine\ORM\QueryAdapter;
use Pagerfanta\Pagerfanta;

/**
 * MovieRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovieRepository extends ServiceEntityRepository
{
    /**
     * @param ManagerRegistry $registry
     */
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Movie::class);
    }

    /**
     * @param string $title
     * @param int $page
     * @param int $maxPerPage
     *
     * @return Pagerfanta
     */
    public function getPager(?string $title = null, int $page = 1, int $maxPerPage = 20): Pagerfanta
    {
        $queryBuilder = $this->createQueryBuilder('movie');

        if (null !== $title) {
            $queryBuilder->andWhere(sprintf('movie.title like \'%%%s%%\'', $title));
        }

        $queryBuilder->orderBy('movie.title');

        $paginator = new Pagerfanta(new QueryAdapter($queryBuilder));
        $paginator->setMaxPerPage($maxPerPage);
        $paginator->setCurrentPage($page);

        return $paginator;
    }

    /**
     * @param int $tmdbId
     *
     * @return Movie[]|array
     */
    public function findByGenre(int $tmdbId): array
    {
        $queryBuilder = $this->createQueryBuilder('movie');

        $queryBuilder
            ->innerJoin('movie.genres', 'genre')
            ->where('genre.tmdbId = :genreId')
            ->setParameter('genreId', $tmdbId)
            ->orderBy('movie.title')
        ;

        return $queryBuilder->getQuery()->getResult();
    }
}
